//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liberty_Jadi.EntityModelAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
    
        public int CountryId { get; set; }
        public string Country_Name { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<State> STATEs { get; set; }
    }
}
