//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liberty_Jadi.EntityModelAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseRegistration
    {
    
        public long CourseRegistrationId { get; set; }
        public long Student_Id { get; set; }
        public int Level_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
        public int Session_Id { get; set; }
        public int Semester_Id { get; set; }
        public Nullable<System.DateTime> Date_Registered { get; set; }
        public long Course_Id { get; set; }
        public Nullable<double> Test_Score { get; set; }
        public Nullable<double> Exam_Score { get; set; }
        public Nullable<double> Total_Score { get; set; }
        public Nullable<long> Uploader_Id { get; set; }
        public Nullable<System.DateTime> Date_Uploaded { get; set; }
        public Nullable<int> Student_Grade_Id { get; set; }
        public Nullable<bool> Is_Absent { get; set; }
        public string Absent_Reason { get; set; }
    
        public virtual Course COURSE { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual STUDENT_GRADE STUDENT_GRADE { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<StudentResult> STUDENT_RESULT { get; set; }
    }
}
