//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liberty_Jadi.EntityModelAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalGovernment
    {
    
        public int LocalGovernmentId { get; set; }
        public string Local_Government_Name { get; set; }
        public string State_Id { get; set; }
    
        public virtual STATE STATE { get; set; }
        public virtual ICollection<PERSON> People { get; set; }
    }
}
