//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liberty_Jadi.EntityModelAccess.Entity
{
    using System;
    using System.Collections.Generic;
    using static Transcript_Processsor.Models.Entities.EnumsClass;

    public partial class Person
    { 


        public long PersonId { get; set; }
        public int Person_Type_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public string Initial { get; set; }
        public Nullable<int> Title_Id { get; set; }
        public string Passport_Url { get; set; }
        public string Signature_Image_Url { get; set; }
        public Nullable<int> Gender_Id { get; set; }
        public string Contact_Address { get; set; }
        public string Email_Address { get; set; }
        public string Mobile_Phone { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string State_Id { get; set; }
        public Nullable<int> Local_Government_Id { get; set; }
        public string Home_Town { get; set; }
        public string Home_Address { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public Nullable<int> Religion_Id { get; set; }
        public System.DateTime Date_Entered { get; set; }
        public int Role_Id { get; set; }
        public Nullable<int> Genotype_Id { get; set; }
        public Nullable<int> Disability_Id { get; set; }
        public Nullable<int> Tribe_Id { get; set; }
        public string ParentName { get; set; }
        public string ParentNumber { get; set; }
        public string Family_Kindred { get; set; }
        public string Village { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
      
        public virtual LocalGovernment LOCAL_GOVERNMENT { get; set; }
     
        public virtual Role ROLE { get; set; }
        public virtual State STATE { get; set; }

        public virtual ICollection<USER> USERs { get; set; }
    }
}
