//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liberty_Jadi.EntityModelAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public string StateId { get; set; }
        public string State_Name { get; set; }
        public int Nationality_Id { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual ICollection<LOCAL_GOVERNMENT> LOCAL_GOVERNMENT { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<TranscriptRequest> TRANSCRIPT_REQUEST { get; set; }
    }
}
