//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liberty_Jadi.EntityModelAccess.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class StudentResult
    {

        public long StudentResultId { get; set; }
        public long Course_Registration_Id { get; set; }
        public Nullable<double> Test_Score { get; set; }
        public Nullable<double> Exam_Score { get; set; }
        public long Uploader_Id { get; set; }
        public System.DateTime Date_Uploaded { get; set; }
        public int Student_Grade_Id { get; set; }
        public Nullable<double> Total_Score { get; set; }
        [ForeignKey("Course_Registration_Id")]
        public virtual CourseRegistration COURSE_REGISTRATION { get; set; }
        [ForeignKey("Student_Grade_Id")]
        public virtual STUDENT_GRADE STUDENT_GRADE { get; set; }
        [ForeignKey("Uploader_Id")]
        public virtual USER USER { get; set; }
    }
}
