//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liberty_Jadi.EntityModelAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranscriptClearanceStatus
    {

        public int TranscriptclearanceStatusId { get; set; }
        public string Transcriptclearance_Status_Name { get; set; }
        public string Transcript_clearance_Status_Description { get; set; }
    
        public virtual ICollection<TranscriptRequest> TRANSCRIPT_REQUEST { get; set; }
    }
}
